/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanaLogin;

import VentanaPrincipal.VentanaMain;
import com.mysql.cj.protocol.Message;
import java.awt.*;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.ByteArrayInputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import persistencia.ConexionBD;
import VentanaLogin.IniciarSesion;
/**
 *
 * @author kevin
 */
public class VentanaLogin extends javax.swing.JFrame {

    private IniciarSesion iniciarSesion;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());

    /**
     * Creates new form VentanaLogin
     */

    public JFrame frame = new JFrame();

    public VentanaLogin() {
        initComponents();
        iniciarSesion = new IniciarSesion(this); // le pasamos la ventana
        barraslister();


    }
    public void abrirVentanaPrincipal() {
        VentanaMain ventana = new VentanaMain();
        ventana.setVisible(true);
        this.dispose(); // Cierra la ventana actual si quieres
    }

    public void aplicarPlaceholder(JTextField campo, String placeholder) {


        // Color gris claro para placeholder
        Color colorPlaceholder = Color.WHITE;

        // Establecer texto y color inicial del placeholder
        campo.setText(placeholder);
        campo.setForeground(colorPlaceholder);

        campo.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText("");
                    campo.setForeground(new Color(130,130,130));
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(placeholder);
                    campo.setForeground(colorPlaceholder);
                }
            }
        });


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        TextoContraseña = new javax.swing.JLabel();
        TextoCorreo_electroinco = new javax.swing.JLabel();
        IconoUser = new javax.swing.JLabel();
        TextoIniciarSesion = new javax.swing.JLabel();
        BarraIngresarCorreo = new javax.swing.JTextField();
        BarraIngresarContraseña = new javax.swing.JPasswordField();
        BtnIniciarSesion = new javax.swing.JPanel();
        TxtBotonIniciar = new javax.swing.JLabel();
        FondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        TextoContraseña.setText("Contraseña:");
        PanelLogin.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        TextoCorreo_electroinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextoCorreo_electroinco.setForeground(new java.awt.Color(255, 255, 255));
        TextoCorreo_electroinco.setText("Correo electronico:");
        PanelLogin.add(TextoCorreo_electroinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        IconoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil-de-usuario .png"))); // NOI18N
        PanelLogin.add(IconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1010, 160));

        TextoIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextoIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        TextoIniciarSesion.setText("INICIAR SESIÓN");
        PanelLogin.add(TextoIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 150, 30));

        BarraIngresarCorreo.setBackground(new java.awt.Color(227, 227, 227));
        BarraIngresarCorreo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        BarraIngresarCorreo.setForeground(new java.awt.Color(255, 255, 255));
        BarraIngresarCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BarraIngresarCorreo.setText("Ingrese su correo electronico");
        BarraIngresarCorreo.setToolTipText("");
        BarraIngresarCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        BarraIngresarCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarraIngresarCorreo.setOpaque(true);
        BarraIngresarCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BarraIngresarCorreoFocusGained(evt);
            }
        });
        BarraIngresarCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarraIngresarCorreoMouseClicked(evt);
            }
        });
        PanelLogin.add(BarraIngresarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 310, 40));

        BarraIngresarContraseña.setBackground(new java.awt.Color(227, 227, 227));
        BarraIngresarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BarraIngresarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        BarraIngresarContraseña.setText("••••••••••••••••");
        BarraIngresarContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        BarraIngresarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarraIngresarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BarraIngresarContraseñaFocusGained(evt);
            }
        });
        BarraIngresarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarraIngresarContraseñaMouseClicked(evt);
            }
        });
        PanelLogin.add(BarraIngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 310, 40));

        BtnIniciarSesion.setBackground(new java.awt.Color(227, 227, 227));

        TxtBotonIniciar.setBackground(new java.awt.Color(227, 227, 227));
        TxtBotonIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtBotonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        TxtBotonIniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtBotonIniciar.setText("Iniciar");
        TxtBotonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtBotonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtBotonIniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtBotonIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtBotonIniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtBotonIniciarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BtnIniciarSesionLayout = new javax.swing.GroupLayout(BtnIniciarSesion);
        BtnIniciarSesion.setLayout(BtnIniciarSesionLayout);
        BtnIniciarSesionLayout.setHorizontalGroup(
            BtnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtBotonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        BtnIniciarSesionLayout.setVerticalGroup(
            BtnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtBotonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelLogin.add(BtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 130, 30));

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogingris.png"))); // NOI18N
        FondoLogin.setMaximumSize(new java.awt.Dimension(1900, 1200));
        PanelLogin.add(FondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1074, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBotonIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBotonIniciarMouseEntered
        BtnIniciarSesion.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_TxtBotonIniciarMouseEntered

    private void TxtBotonIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBotonIniciarMouseExited
        BtnIniciarSesion.setBackground(new Color(227,227,227));
        TxtBotonIniciar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_TxtBotonIniciarMouseExited

    private void TxtBotonIniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBotonIniciarMousePressed
        BtnIniciarSesion.setBackground(new Color(223,223,223));
        TxtBotonIniciar.setForeground(new Color(235,235,235));
    }//GEN-LAST:event_TxtBotonIniciarMousePressed

    private void BarraIngresarCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraIngresarCorreoMouseClicked
        BarraIngresarCorreo.setText("");
        BarraIngresarCorreo.setForeground(new Color(130,130,130));
    }//GEN-LAST:event_BarraIngresarCorreoMouseClicked

    private void BarraIngresarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraIngresarContraseñaMouseClicked
        BarraIngresarContraseña.setText("");
        BarraIngresarContraseña.setForeground(new Color(130,130,130));
    }//GEN-LAST:event_BarraIngresarContraseñaMouseClicked

    private void BarraIngresarCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BarraIngresarCorreoFocusGained
        aplicarPlaceholder(BarraIngresarCorreo,"Ingrese su correo electronico");
    }//GEN-LAST:event_BarraIngresarCorreoFocusGained

    private void BarraIngresarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BarraIngresarContraseñaFocusGained
        BarraIngresarContraseña.addFocusListener(new FocusAdapter()
        {
            @Override
            public void focusGained(FocusEvent e) {
                if (BarraIngresarContraseña.getText().equals("••••••••••••••••")) {
                    BarraIngresarContraseña.setText("");
                    BarraIngresarContraseña.setForeground(new Color(130,130,130));
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (BarraIngresarContraseña.getText().isEmpty()) {
                    BarraIngresarContraseña.setText("••••••••••••••••");
                    BarraIngresarContraseña.setForeground(Color.WHITE);
                }
            }
        });
    }//GEN-LAST:event_BarraIngresarContraseñaFocusGained

    private void TxtBotonIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBotonIniciarMouseClicked
        iniciarSesion.Login();
    }//GEN-LAST:event_TxtBotonIniciarMouseClicked

    public String getCorreoText() {
        return BarraIngresarCorreo.getText();
    }

    public String getPasswordText() {
        return new String(BarraIngresarContraseña.getPassword());
    }

    void barraslister(){
        BarraIngresarCorreo.addActionListener(iniciarSesion.Login());
        BarraIngresarContraseña.addActionListener(iniciarSesion.Login());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField BarraIngresarContraseña;
    private javax.swing.JTextField BarraIngresarCorreo;
    private javax.swing.JPanel BtnIniciarSesion;
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JLabel IconoUser;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel TextoCorreo_electroinco;
    private javax.swing.JLabel TextoIniciarSesion;
    private javax.swing.JLabel TxtBotonIniciar;
    // End of variables declaration//GEN-END:variables
}
