/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VentanaPrincipal;

import VentanaPrincipal.CerrarSesion;
import VentanaPrincipal.VentanaMain;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kevin
 */
public class MenuEmpleado extends javax.swing.JPanel {

    private VentanaPrincipal.CerrarSesion sesion;
    private VentanaPrincipal.VentanaMain ventanaMain;
    private Botones botones;
    
    public MenuEmpleado(VentanaMain ventanaMain) {
        this.ventanaMain = ventanaMain; 
        initComponents();      
        sesion = new CerrarSesion(ventanaMain);
        botones = new Botones(ventanaMain, this);
        botonesescucha();
    }

    public void botonesescucha(){

        botones.botonesEmpleados(DatosPersonalesBtn,DatosPersonalesTxt,0,"VnDatosClientes");
        botones.botonesEmpleados(GestionProductosBtn,GestionProductosTxt,1,"VnGestionProductos");
        botones.botonesEmpleados(FacturacionBtn,FacturacionTxt,2,"VnFacturacion");
        botones.botonesEmpleados(HistorialClienteBtn,HistorialClienteTxt,3,"VnHistorialCliente");
    }
    public void IluminacionBotonesMenuEmpleado(JPanel botonActivo, JLabel Txt) {

        JPanel[] botones = {DatosPersonalesBtn, GestionProductosBtn, FacturacionBtn, HistorialClienteBtn};
        JLabel[] botonetxt = {DatosPersonalesTxt, GestionProductosTxt, FacturacionTxt, HistorialClienteTxt};
        
        
        for (JPanel boton : botones) {
            // activo
            if (boton == botonActivo) {
                boton.setBackground(new Color(230,230,230));
            }
            // inactivo
            else if (boton != botonActivo) {
                boton.setBackground(new Color(220,220,220));             
            }
        }
        for (JLabel Texto : botonetxt){
            if(Texto == Txt){
                Texto.setForeground(new Color(255,255,255));
            }
            else if(Texto != Txt){
                Texto.setForeground(new Color(102,102,102));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_empleadoMenu = new javax.swing.JLabel();
        DatosPersonalesBtn = new BordesSuaves.PanelRound();
        DatosPersonalesTxt = new javax.swing.JLabel();
        HistorialClienteBtn = new BordesSuaves.PanelRound();
        HistorialClienteTxt = new javax.swing.JLabel();
        FacturacionBtn = new BordesSuaves.PanelRound();
        FacturacionTxt = new javax.swing.JLabel();
        GestionProductosBtn = new BordesSuaves.PanelRound();
        GestionProductosTxt = new javax.swing.JLabel();
        LogoEmpresa = new javax.swing.JLabel();
        CerrarSesionBtn1 = new javax.swing.JLabel();
        FondoMenuEmpleado = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(270, 750));
        setMinimumSize(new java.awt.Dimension(270, 770));
        setPreferredSize(new java.awt.Dimension(270, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre_empleadoMenu.setBackground(new java.awt.Color(102, 102, 102));
        Nombre_empleadoMenu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Nombre_empleadoMenu.setForeground(new java.awt.Color(102, 102, 102));
        Nombre_empleadoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_empleadoMenu.setText("Nombre empleado");
        Nombre_empleadoMenu.setMaximumSize(new java.awt.Dimension(59, 50));
        add(Nombre_empleadoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, -1));

        DatosPersonalesBtn.setBackground(new java.awt.Color(230, 230, 230));
        DatosPersonalesBtn.setMaximumSize(new java.awt.Dimension(250, 60));
        DatosPersonalesBtn.setMinimumSize(new java.awt.Dimension(250, 60));
        DatosPersonalesBtn.setRoundBottomLeft(30);
        DatosPersonalesBtn.setRoundBottomRight(30);
        DatosPersonalesBtn.setRoundTopLeft(30);
        DatosPersonalesBtn.setRoundTopRight(30);

        DatosPersonalesTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        DatosPersonalesTxt.setForeground(new java.awt.Color(255, 255, 255));
        DatosPersonalesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatosPersonalesTxt.setText("Datos Personales");
        DatosPersonalesTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout DatosPersonalesBtnLayout = new javax.swing.GroupLayout(DatosPersonalesBtn);
        DatosPersonalesBtn.setLayout(DatosPersonalesBtnLayout);
        DatosPersonalesBtnLayout.setHorizontalGroup(
            DatosPersonalesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DatosPersonalesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        DatosPersonalesBtnLayout.setVerticalGroup(
            DatosPersonalesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DatosPersonalesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(DatosPersonalesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 250, 60));

        HistorialClienteBtn.setBackground(new java.awt.Color(220, 220, 220));
        HistorialClienteBtn.setMaximumSize(new java.awt.Dimension(250, 60));
        HistorialClienteBtn.setMinimumSize(new java.awt.Dimension(250, 60));
        HistorialClienteBtn.setRoundBottomLeft(30);
        HistorialClienteBtn.setRoundBottomRight(30);
        HistorialClienteBtn.setRoundTopLeft(30);
        HistorialClienteBtn.setRoundTopRight(30);

        HistorialClienteTxt.setBackground(new java.awt.Color(198, 198, 198));
        HistorialClienteTxt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        HistorialClienteTxt.setForeground(new java.awt.Color(102, 102, 102));
        HistorialClienteTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HistorialClienteTxt.setText("Historial del Cliente");
        HistorialClienteTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout HistorialClienteBtnLayout = new javax.swing.GroupLayout(HistorialClienteBtn);
        HistorialClienteBtn.setLayout(HistorialClienteBtnLayout);
        HistorialClienteBtnLayout.setHorizontalGroup(
            HistorialClienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistorialClienteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        HistorialClienteBtnLayout.setVerticalGroup(
            HistorialClienteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistorialClienteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(HistorialClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 250, 60));

        FacturacionBtn.setBackground(new java.awt.Color(220, 220, 220));
        FacturacionBtn.setMaximumSize(new java.awt.Dimension(250, 60));
        FacturacionBtn.setMinimumSize(new java.awt.Dimension(250, 60));
        FacturacionBtn.setRoundBottomLeft(30);
        FacturacionBtn.setRoundBottomRight(30);
        FacturacionBtn.setRoundTopLeft(30);
        FacturacionBtn.setRoundTopRight(30);

        FacturacionTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        FacturacionTxt.setForeground(new java.awt.Color(102, 102, 102));
        FacturacionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FacturacionTxt.setText("Facturación");
        FacturacionTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout FacturacionBtnLayout = new javax.swing.GroupLayout(FacturacionBtn);
        FacturacionBtn.setLayout(FacturacionBtnLayout);
        FacturacionBtnLayout.setHorizontalGroup(
            FacturacionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FacturacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        FacturacionBtnLayout.setVerticalGroup(
            FacturacionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FacturacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(FacturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 250, 60));

        GestionProductosBtn.setBackground(new java.awt.Color(220, 220, 220));
        GestionProductosBtn.setMaximumSize(new java.awt.Dimension(250, 60));
        GestionProductosBtn.setMinimumSize(new java.awt.Dimension(250, 60));
        GestionProductosBtn.setRoundBottomLeft(30);
        GestionProductosBtn.setRoundBottomRight(30);
        GestionProductosBtn.setRoundTopLeft(30);
        GestionProductosBtn.setRoundTopRight(30);

        GestionProductosTxt.setBackground(new java.awt.Color(198, 198, 198));
        GestionProductosTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        GestionProductosTxt.setForeground(new java.awt.Color(102, 102, 102));
        GestionProductosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GestionProductosTxt.setText("Gestión de productos");
        GestionProductosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout GestionProductosBtnLayout = new javax.swing.GroupLayout(GestionProductosBtn);
        GestionProductosBtn.setLayout(GestionProductosBtnLayout);
        GestionProductosBtnLayout.setHorizontalGroup(
            GestionProductosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionProductosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        GestionProductosBtnLayout.setVerticalGroup(
            GestionProductosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionProductosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(GestionProductosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 250, 60));

        LogoEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        LogoEmpresa.setToolTipText("");
        add(LogoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 155));

        CerrarSesionBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        CerrarSesionBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesionBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionBtn1MouseClicked(evt);
            }
        });
        add(CerrarSesionBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        FondoMenuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        FondoMenuEmpleado.setMaximumSize(new java.awt.Dimension(270, 770));
        FondoMenuEmpleado.setMinimumSize(new java.awt.Dimension(270, 770));
        FondoMenuEmpleado.setPreferredSize(new java.awt.Dimension(270, 770));
        add(FondoMenuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));
    }// </editor-fold>//GEN-END:initComponents

    
    private void CerrarSesionBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionBtn1MouseClicked
        sesion.CerrarSesionMain();
    }//GEN-LAST:event_CerrarSesionBtn1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesionBtn1;
    private BordesSuaves.PanelRound DatosPersonalesBtn;
    private javax.swing.JLabel DatosPersonalesTxt;
    private BordesSuaves.PanelRound FacturacionBtn;
    private javax.swing.JLabel FacturacionTxt;
    private javax.swing.JLabel FondoMenuEmpleado;
    private BordesSuaves.PanelRound GestionProductosBtn;
    private javax.swing.JLabel GestionProductosTxt;
    private BordesSuaves.PanelRound HistorialClienteBtn;
    private javax.swing.JLabel HistorialClienteTxt;
    private javax.swing.JLabel LogoEmpresa;
    private javax.swing.JLabel Nombre_empleadoMenu;
    // End of variables declaration//GEN-END:variables
}
