/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanaEmergenteAdministrador;

import javax.swing.JFrame;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author kevin
 */
public class VentanaEmergenteEditarEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEmergenteEditarEmpleado.class.getName());

    /**
     * Creates new form VentanaEmergenteEditarEmpleado
     */
    public VentanaEmergenteEditarEmpleado() {

        JFrame frame = new JFrame();
        frame.setSize(860, 512);
        frame.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonEditarEmpleado = new BordesSuaves.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        BarraEditarNombreEmpleado_VentanaEmergente = new javax.swing.JTextField();
        BarraEditarCedulaEmpleado_VentanaEmergente = new javax.swing.JTextField();
        BarraEditarTelefonoEmpleado_VentanaEmergente = new javax.swing.JTextField();
        BoxEditarCargoEmpleado_VentanaEmergente = new javax.swing.JComboBox<>();
        BarraEditarUsuarioEmpleado_VentanaEmergente = new javax.swing.JTextField();
        BoxEditarNivelAccesoEmpleado_VentanaEmergente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BarraEditarContraseñaEmpleado_VentanaEmergente = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonEditarEmpleado.setBackground(new java.awt.Color(220, 220, 220));
        BotonEditarEmpleado.setRoundBottomLeft(30);
        BotonEditarEmpleado.setRoundBottomRight(30);
        BotonEditarEmpleado.setRoundTopLeft(30);
        BotonEditarEmpleado.setRoundTopRight(30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Editar");

        javax.swing.GroupLayout BotonEditarEmpleadoLayout = new javax.swing.GroupLayout(BotonEditarEmpleado);
        BotonEditarEmpleado.setLayout(BotonEditarEmpleadoLayout);
        BotonEditarEmpleadoLayout.setHorizontalGroup(
            BotonEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        BotonEditarEmpleadoLayout.setVerticalGroup(
            BotonEditarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        BarraEditarNombreEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BarraEditarNombreEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraEditarNombreEmpleado_VentanaEmergente.setText("Introduce el nuevo nombre");

        BarraEditarCedulaEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BarraEditarCedulaEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraEditarCedulaEmpleado_VentanaEmergente.setText("Introuce la nueva cedula");

        BarraEditarTelefonoEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BarraEditarTelefonoEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraEditarTelefonoEmpleado_VentanaEmergente.setText("Introduce el nuevo telefono");

        BoxEditarCargoEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BoxEditarCargoEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BoxEditarCargoEmpleado_VentanaEmergente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));

        BarraEditarUsuarioEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BarraEditarUsuarioEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraEditarUsuarioEmpleado_VentanaEmergente.setText("Introduce el nuevo correo o usuario");

        BoxEditarNivelAccesoEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BoxEditarNivelAccesoEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BoxEditarNivelAccesoEmpleado_VentanaEmergente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Administrador" }));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Editar nombre del empleado");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Editar cedula del empleado");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Editor de datos del empleado");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Editar correo o usuario del empleado");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Editar contraseña del empleado");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Editar telefono del empleado");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Editar nievel de acceso");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Editar cargo del empleado");

        BarraEditarContraseñaEmpleado_VentanaEmergente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BarraEditarContraseñaEmpleado_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraEditarContraseñaEmpleado_VentanaEmergente.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(274, 274, 274)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BarraEditarNombreEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(BarraEditarUsuarioEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addGap(278, 278, 278)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BarraEditarCedulaEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(BarraEditarContraseñaEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BarraEditarTelefonoEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(BoxEditarNivelAccesoEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BoxEditarCargoEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(709, 709, 709)
                        .addComponent(BotonEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraEditarNombreEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BarraEditarUsuarioEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraEditarCedulaEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BarraEditarContraseñaEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraEditarTelefonoEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxEditarNivelAccesoEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(BoxEditarCargoEmpleado_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BarraEditarCedulaEmpleado_VentanaEmergente;
    public javax.swing.JPasswordField BarraEditarContraseñaEmpleado_VentanaEmergente;
    public javax.swing.JTextField BarraEditarNombreEmpleado_VentanaEmergente;
    public javax.swing.JTextField BarraEditarTelefonoEmpleado_VentanaEmergente;
    public javax.swing.JTextField BarraEditarUsuarioEmpleado_VentanaEmergente;
    public BordesSuaves.PanelRound BotonEditarEmpleado;
    public javax.swing.JComboBox<String> BoxEditarCargoEmpleado_VentanaEmergente;
    public javax.swing.JComboBox<String> BoxEditarNivelAccesoEmpleado_VentanaEmergente;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
