/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VentanaEmergenteAdministrador;

/**
 *
 * @author kevin
 */
public class VentanaEmergenteAgregarCorreo extends javax.swing.JPanel {

    /**
     * Creates new form VentanaEmergenteAgregarCorreo
     */
    public VentanaEmergenteAgregarCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BarraCrearUsuario_VentanaEmergente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BoxNivelAcceso_VentanaEmergente = new javax.swing.JComboBox<>();
        BarraCrearContraseña_VentanaEmergente = new javax.swing.JPasswordField();
        BotonAgregarUsuarioContraseña = new BordesSuaves.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Creale su cuenta");

        BarraCrearUsuario_VentanaEmergente.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        BarraCrearUsuario_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraCrearUsuario_VentanaEmergente.setText("Ingrese un nuevo correo o usuario");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Correo o Usuario");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        BoxNivelAcceso_VentanaEmergente.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        BoxNivelAcceso_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BoxNivelAcceso_VentanaEmergente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Administrador" }));

        BarraCrearContraseña_VentanaEmergente.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        BarraCrearContraseña_VentanaEmergente.setForeground(new java.awt.Color(51, 51, 51));
        BarraCrearContraseña_VentanaEmergente.setText("jPasswordField1");

        BotonAgregarUsuarioContraseña.setBackground(new java.awt.Color(220, 220, 220));
        BotonAgregarUsuarioContraseña.setRoundBottomLeft(30);
        BotonAgregarUsuarioContraseña.setRoundBottomRight(30);
        BotonAgregarUsuarioContraseña.setRoundTopLeft(30);
        BotonAgregarUsuarioContraseña.setRoundTopRight(30);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar");

        javax.swing.GroupLayout BotonAgregarUsuarioContraseñaLayout = new javax.swing.GroupLayout(BotonAgregarUsuarioContraseña);
        BotonAgregarUsuarioContraseña.setLayout(BotonAgregarUsuarioContraseñaLayout);
        BotonAgregarUsuarioContraseñaLayout.setHorizontalGroup(
            BotonAgregarUsuarioContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        BotonAgregarUsuarioContraseñaLayout.setVerticalGroup(
            BotonAgregarUsuarioContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nivel de Acceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoxNivelAcceso_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(BotonAgregarUsuarioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(BarraCrearUsuario_VentanaEmergente, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(BarraCrearContraseña_VentanaEmergente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraCrearUsuario_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraCrearContraseña_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonAgregarUsuarioContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BoxNivelAcceso_VentanaEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField BarraCrearContraseña_VentanaEmergente;
    public javax.swing.JTextField BarraCrearUsuario_VentanaEmergente;
    public BordesSuaves.PanelRound BotonAgregarUsuarioContraseña;
    public javax.swing.JComboBox<String> BoxNivelAcceso_VentanaEmergente;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
